name: Build APK

on:
  push:
    branches:
      - main  # adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-pip \
          python3-setuptools \
          python3-venv \
          zlib1g-dev \
          libjpeg-dev \
          libtiff-dev \
          libsdl2-dev \
          libgstreamer-plugins-base1.0-dev \
          libnotify-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.0-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libprotobuf-dev \
          protobuf-compiler \
          libgles2-mesa-dev \
          libegl1-mesa-dev \
          libgstreamer-plugins-bad1.0-dev \
          libtheora-dev \
          libgstreamer-plugins-good1.0-dev \
          libavcodec-dev \
          libavformat-dev \
          libswscale-dev \
          libavdevice-dev \
          libavutil-dev \
          libavresample-dev \
          libfreetype6-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswresample-dev \
          libpostproc-dev \
          libxrandr-dev \
          libxrender-dev \
          libxcb1-dev \
          libffi-dev \
          libxml2-dev \
          libxslt1-dev \
          libjpeg-dev \
          zlib1g-dev \
          libpq-dev \
          libssl-dev \
          libsqlite3-dev \
          libbz2-dev \
          libreadline-dev \
          libncursesw5-dev \
          liblzma-dev \
          libffi-dev \
          libncurses5 \
          libncursesw5 \
          libtinfo5 \
          zlib1g \
          libbz2-1.0 \
          libsqlite3-0 \
          libssl1.1 \
          libreadline7 \
          libncursesw6 \
          libtinfo6 \
          liblzma5 \
          libffi6 \
          zlib1g-dev \
          libffi-dev \
          python3-dev
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: |
        buildozer init
        cp main.py
        buildozer -v android debug
