name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Operating System
        run: |
          echo "Operating System: ${{ runner.os }}"
