name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      # Get the current date
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      # Cache Buildozer global directory
      - uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer local directory
      - uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Set GIT_CONFIG
        env: 
          GIT_CONFIG: .gitconfig  # Replace with the actual path
        run: |
          echo "Using separate GIT_CONFIG: ${{ env.GIT_CONFIG }}"

      # Install AIDL (Android Interface Definition Language)
      - name: Install AIDL
        run: |
          sudo apt-get update
          sudo apt-get install -y aidl
          which aidl  # Debugging: Verify if AIDL is in the PATH

      # Build with Buildozer
      - name: Build with Buildozer
        run: |
          buildozer --version  # Debugging: Verify Buildozer version
          echo y | buildozer -v android debug  # Debugging: Try running the Buildozer command directly

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package

